export { default as System } from './System'
export { default as CreatePost } from './CreatePost'
export { default as Header } from './Header'
export { default as Sidebar } from './Sidebar'
export { default as ManagePost } from './ManagePost'
export { default as EditAccount } from './EditAccount'
// export { default as PayPost } from './PayPost'