const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    GET_POSTS: "GET_POSTS",
    GET_POSTS_PAGE: "GET_POSTS_PAGE",
    GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
    GET_NEW_POST: "GET_NEW_POST",

    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_PRICES: 'GET_PRICES',
    GET_AREAS: 'GET_AREAS',
    GET_PROVINCES: 'GET_PROVINCES',

    // USER
    GET_CURRENT: 'GET_CURRENT',

    //ADMIN
    LOGIN_ADMIN_SUCCESS:'LOGIN_ADMIN_SUCCESS',
    LOGIN_ADMIN_FAIL: 'LOGIN_ADMIN_FAIL',
    LOGOUT_ADMIN: 'LOGOUT_ADMIN',
    GET_ONEPOST: 'GET_ONEPOST',
}

export default actionTypes