const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    GET_POSTS: "GET_POSTS",
    GET_POSTS_PAGE: "GET_POSTS_PAGE",
    GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
    GET_POSTS_ADMIN: "GET_POSTS_ADMIN",
    GET_NEW_POST: "GET_NEW_POST",
    EDIT_DATA: 'EDIT-DATA',
    RESET_DATAEDIT: 'RESET_DATAEDIT',

    EDIT_ACCOUNT: 'EDIT_ACCOUNT',

    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_PRICES: 'GET_PRICES',
    GET_AREAS: 'GET_AREAS',
    GET_PROVINCES: 'GET_PROVINCES',

    // USER
    GET_CURRENT: 'GET_CURRENT',
    GET_USER:'GET_USER',
    GET_ONE_USER:'Get_ONE_USER',
    EDIT_ACCOUNT: 'EDIT_ACCOUNT',

    //ADMIN
    LOGIN_ADMIN_SUCCESS:'LOGIN_ADMIN_SUCCESS',
    LOGIN_ADMIN_FAIL: 'LOGIN_ADMIN_FAIL',
    LOGOUT_ADMIN: 'LOGOUT_ADMIN',
    GET_ONEPOST: 'GET_ONEPOST',
    UPDATE_POST:'UPDATE_POST',
    GET_PENPOST:'GET_PENPOST',
    GET_ACCPOST:'GET_ACCPOST',
    GET_REJPOST:'GET_REJPOST',
    UPDATE_STATUS_POST:'UPDATE_STATUS_POST',
}

export default actionTypes